SSH_USER = # Fill this
SSH_HOST = # Fill this

ROOT_DIR := $(dir $(realpath $(lastword $(MAKEFILE_LIST))))
PROJECT_ROOT := $(abspath $(ROOT_DIR)/..)

NAME = vktexbot
APP_DIR = /tmp/vktexbot_build

VERSION := $(shell git describe --tags --abbrev=0 2> /dev/null)

FORCE_BUILD ?= false

build_remote:
	@if [ "$(FORCE_BUILD)" = "true" ] || ! ssh $(SSH_USER)@$(SSH_HOST) "docker inspect --format='ok' $(NAME)-image:$(VERSION) >/dev/null 2>&1"; then \
		echo "Building image $(NAME)-image:$(VERSION)"; \
		ssh $(SSH_USER)@$(SSH_HOST) "mkdir -p $(APP_DIR)"; \
		rsync -avz $(PROJECT_ROOT)/ $(SSH_USER)@$(SSH_HOST):$(APP_DIR); \
		ssh $(SSH_USER)@$(SSH_HOST) " \
			cd $(APP_DIR) && \
			docker build -f deploy/Dockerfile -t $(NAME)-image:$(VERSION) . && \
			rm -rf $(APP_DIR)"; \
	else \
		echo "Image $(NAME)-image:$(VERSION) already exists. Skipping build."; \
	fi

deploy: build_remote
	ssh $(SSH_USER)@$(SSH_HOST) "\
		docker stop $(NAME) 2>/dev/null || true; \
		docker rm $(NAME) 2>/dev/null || true; \
		docker run -d \
			--name $(NAME) \
			--restart unless-stopped \
			-v /var/log/$(NAME):/var/log/$(NAME) \
			$(NAME)-image:$(VERSION)"
